"""transactions: add external_id

Revision ID: 7896955c1e1c
Revises: bf143bfd443f
Create Date: 2026-10-02 12:20:03.938084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7896955c1e1c'
down_revision: Union[str, Sequence[str], None] = 'bf143bfd443f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'external_id')
    # ### end Alembic commands ###
