"""accounts: balance_as_of

Revision ID: cf5b5853ca89
Revises: 9b25a94a29a4
Create Date: 2026-09-29 12:14:04.828026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5b5853ca89'
down_revision: Union[str, Sequence[str], None] = '9b25a94a29a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('accounts', sa.Column('balance_as_of', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'balance_as_of')
    op.drop_column('accounts', 'balance')
    # ### end Alembic commands ###
